from prep import constants as PC
SYNTH_SEED = 20260704
PROMPT_VERSION = 'initial-v1'
PROMPT_SHA256 = 'b8b135f655a362b6ebd282cf23d330b83ccdf0a9d38aa35040a899b8cdc803fe'
MODEL_PRESETS = {'mini': {'snapshot': 'gpt-5.4-mini-2026-03-17', 'effort': 'medium', 'price_in': 0.375, 'price_cached_in': 0.038, 'price_out': 2.25}}
DEFAULT_PRESET = 'mini'
STYLE_PERSONA = {'lowercase_i': 0.22, 'drops_apostrophes': 0.12, 'swears': 0.22, 'no_terminal_punct': 0.31}
STYLE_POST = {'question': 0.215, 'asks_community': 0.12, 'second_person': 0.165, 'future_ref': 0.31, 'ellipsis': 0.105, 'exclamation': 0.04, 'paragraph_break': 0.075, 'opens_with_i': 0.334}
STYLE_COMMA_BY_LEN = ((25, 0.13), (60, 0.36), (150, 0.64), (None, 0.84))
STYLE_ANCHORS = (('', 0.73), ('today', 0.093), ('soon', 0.07), ('tonight', 0.041), ('tomorrow', 0.035), ('next week', 0.009), ('monday', 0.006), ('tuesday', 0.004), ('this week', 0.004), ('wednesday', 0.003), ('this weekend', 0.002), ('next month', 0.002), ('friday', 0.001))
RARE_FACTORS = ('cognitive deficits', 'substance use', 'poor school performance', "exposure to others' suicide", 'sexual orientation related issues', 'meaning in life')
FACTOR_SLUGS = {'cognitive deficits': 'cogdef', 'substance use': 'subst', 'poor school performance': 'school', "exposure to others' suicide": 'exposure', 'sexual orientation related issues': 'sexor', 'meaning in life': 'meaning'}
SLUG_FACTORS = {v: k for k, v in FACTOR_SLUGS.items()}
POOLS = ('0', '1', '2', '3', '4', 'full')
SYNTHETIC_POSITIVES_PER_FACTOR = 100
OVERSAMPLE = 1.3
QUOTA_FULL = int(SYNTHETIC_POSITIVES_PER_FACTOR * OVERSAMPLE)
TIMELINE_LEN = (4, 7)
N_TARGET_PROBS = ((1, 0.5), (2, 0.35), (3, 0.15))
POST_LEN_CLAMP = (15, 350)
SPAN_COUNT_MAX = 4
SPAN_TOKENS_MAX = PC.EXPECTED['max_span_tokens']
MAX_BA_SHARE = 0.3
NOISE_VERSION = 'noise-v1'
NOISE = {'curly_apostrophe_given_apos': 0.5, 'curly_doubles': 0.05, 'amp_entity': 0.009, 'typos': 0.15, 'emoji': 0.03, 'sentence_cap_given_capitalizer': 0.92}
CURLY_TARGET_MARGINAL = 0.34
EMOJI_CENSUS = ('😃', '😞', '🤡', '💔', '😭', '😔', '🙃', '🥺')
CURLY_RATE_TOL = 0.05
REAL_STYLE_TARGETS = {'contracted_posts': 0.684, 'dropped_posts': 0.138, 'spelled_posts': 0.362, 'uppercase_posts': 0.835, 'cap_i_posts': 0.687}
STYLE_RATE_TOL = 0.05
CONTRACT = {'full_p': 0.8, 'partial_p': 0.2, 'token_p': 0.6}
DROP_TOKEN_P = 0.7
CONTRACTIONS_DROPPED = {'im': "i'm", 'dont': "don't", 'cant': "can't", 'wont': "won't", 'ive': "i've", 'isnt': "isn't", 'doesnt': "doesn't", 'didnt': "didn't", 'wasnt': "wasn't", 'couldnt': "couldn't", 'wouldnt': "wouldn't", 'shouldnt': "shouldn't", 'havent': "haven't", 'hasnt': "hasn't", 'arent': "aren't", 'youre': "you're", 'theyre': "they're", 'whats': "what's", 'thats': "that's", 'hes': "he's", 'shes': "she's", 'theres': "there's", 'heres': "here's", 'youll': "you'll", 'youve': "you've", 'weve': "we've", 'theyve': "they've", 'theyll': "they'll"}
CONTRACTIONS_SPELLED = {'do not': "don't", 'cannot': "can't", 'can not': "can't", 'will not': "won't", 'does not': "doesn't", 'did not': "didn't", 'is not': "isn't", 'was not': "wasn't", 'are not': "aren't", 'have not': "haven't", 'has not': "hasn't", 'could not': "couldn't", 'would not': "wouldn't", 'should not': "shouldn't", 'i am': "i'm", 'you are': "you're", 'they are': "they're", 'we are': "we're", 'it is': "it's", 'that is': "that's", 'what is': "what's", 'there is': "there's", 'i have': "i've", 'i will': "i'll", 'i would': "i'd"}
SPELLED_UNGUARDED = frozenset({'do not', 'cannot', 'can not', 'will not', 'does not', 'did not', 'is not', 'was not', 'are not', 'have not', 'has not', 'could not', 'would not', 'should not'})
SPELLED_BLOCK_PRECEDING = frozenset({'as', 'than', 'that', 'what', 'who', 'how', 'where'})
IVE_FOLLOWERS = frozenset({'been', 'had', 'got', 'gotten', 'never', 'ever', 'always', 'already', 'just', 'only', 'finally', 'tried', 'started', 'stopped', 'lost', 'felt', 'thought', 'seen', 'done', 'made', 'said', 'told', 'kept', 'spent', 'taken', 'written', 'read', 'failed', 'given', 'gone', 'become', 'known', 'heard', 'hurt', 'cut', 'held', 'left', 'found'})
OVERLAP_NGRAM = 8
REALISM_MAX_AUC = 0.8
PILOT_MAX_REFUSAL = 0.1
PILOT_MIN_METHOD_TERM_RATIO = 0.6
PILOT_MAX_ALIGN_FAIL = 0.05
METHOD_TERMS = ('rope', 'pills', 'overdose', 'od', 'gun', 'bullets', 'bullet', 'hang', 'hanging', 'jump', 'bridge', 'cut', 'cuts', 'cutting', 'blade', 'knife', 'drown', 'poison', 'carbon monoxide', 'helium', 'train', 'cliff', 'wrist', 'wrists', 'paracetamol', 'ibuprofen', 'xanax', 'benadryl', 'insulin')
BATCH_URL = '/v1/responses'
BATCH_COMPLETION_WINDOW = '24h'
MAX_OUTPUT_TOKENS = 16000
TEMPERATURE = 1.0
POLL_INTERVAL_S = 300
SYNC_WORKERS = 8
SYNC_MAX_RETRIES = 5
POST_TOKENS_REJECT = 700
EST_CHARS_PER_TOKEN = 4
EST_OUTPUT_FRAC = 2.2
SYNTH_DIR = 'data/synthetic'
P_MANIFEST = 'manifest.json'
P_BUNDLES = 'bundles.jsonl'
P_EXEMPLARS = 'exemplars.json'
P_REQUESTS = 'requests'
P_BATCH_STATE = 'batch_state.json'
P_RAW = 'raw_responses'
P_PARSED = 'parsed'
P_NOISED = 'noised'
P_FILTERED = 'filtered'
P_POOLS = 'pools'
P_PROVENANCE = 'provenance.jsonl'
P_VALIDATION = 'validation_report.json'
P_REALISM = 'realism_report.json'
P_ARMS = 'arms'
ARMS = ('synthetic', 'repeated_real')
MATCH_ARM = 'synthetic'
FACTOR_DEFINITIONS = {'hopelessness': 'Feelings of hopelessness, or feeling trapped/stuck', 'emotion dysregulation': 'Emotion regulation difficulties (e.g., uncontrolled anxiety, anger)', 'poor social support': 'Lack friends, loneliness, being isolated/rejected/neglected/abandoned', 'low self-esteem': 'Self-negative feelings (e.g., worthlessness, being a burden, self-hate)', 'suicide means (with access)': 'Description of potential means or access to that means', 'mental health issues': 'Existing mental disorders (e.g., depression, personality disorders)', 'prior self-harm or suicidal thought/attempt': 'Past, resolved, previous self-harm and suicidal thought/plan/attempt', 'interpersonal difficulty': 'Having difficulty making new friends, socialization, etc.', 'stressful life event': 'Events that pose challenges but do not lead to traumatic responses', 'dysfunctional family': 'Family-related issues that lead to negative impacts on the individual', 'interpersonal violence': 'Violence or assault, occurring outside home settings', 'physical health/characteristic': 'Physical health issues (e.g., COVID-19, obesity/underweight)', 'traumatic experience': "Event(s) that is overwhelming an individual's ability to cope", 'low socio-economic status': 'Unemployment status, poverty, and homeless, etc.', 'cognitive deficits': 'Having difficulty in cognitive abilities', 'substance use': 'The uncontrollable use of drugs/alcohol/tobacco', 'poor school performance': 'Low school performance (e.g., failing tests, bad grades)', "exposure to others' suicide": "Mentioning or describing others' suicidal thoughts, attempt or death", 'sexual orientation related issues': 'Having gender/sexual disorder, same-sex relationship, etc.', 'coping strategy': 'Activities individuals engage in to deal with stressful situations', 'psychological capital': "Individual's positive psychological state of development", 'social support': 'Support from family, partners, friends, healthcare professionals', 'sense of responsibility': "Awareness of responsibility to one's own health/survival and to others", 'meaning in life': 'Involves cognitive, motivational and affective components'}
assert set(FACTOR_DEFINITIONS) == set(PC.FACTORS_24)
RISK_RULES_TEXT = 'Official class definitions (the annotators\' instructions):\n- Indicator: Post contains no explicit mentions of suicide.\n- Ideation: Post contains explicit suicidal expressions but no suicidal plan.\n- Behavior: Post contains explicit suicidal expressions and self-harm/suicidal plan.\n- Attempt: Post contains explicit mentions of recent/past suicidal attempts.\n\nDecision procedure, applied top-down:\nSTEP 1 - Attempt: the author\'s OWN suicidal/self-harm act actually occurred (past\ntense or in progress): "just overdosed", "attempted last night", aborted attempts\n("tied it around my neck... stopped myself"), recent self-harm relapse, or future\ntense + "again" after a real prior act. Exceptions: past attempts framed as\nrecovery with a positive current stance are Indicator; others\' attempts never count.\nSTEP 2 - Behavior: explicit first-person intent PLUS operational specificity, any\nof: owned/accessible method, method-seeking or lethality question, means\nacquisition ("buying a rope and ending it tomorrow"), a set date/countdown,\nlocation scouting, suicide-note writing, imminent farewell, or ongoing self-harm\ninside a suicidal post. Behavior posts often contain no suicide word at all\n(pure method/lethality questions are Behavior).\nSTEP 3 - Ideation: any explicit first-person death wish without a plan, including\npassive forms ("I pray that I die in my sleep") and no-access counterfactuals\n("if I just had access to a loaded gun..."). Wishing an external agent would kill\nyou stays Ideation - self-administration is the Ideation/Behavior line.\nSTEP 4 - Indicator: distress of any intensity without an explicit death word\n("It never gets better"), veiled phrases alone ("don\'t want to be here", "tired\nof living"), and all negated / recovered / third-person suicide mentions. A\ntrailing negation overrides everything before it ("But i dont want to die").\n\nBoundary rules in one line each:\n- Indicator vs Ideation: lexical explicitness, not severity - an unnegated\n  first-person death/suicide word means Ideation.\n- Ideation vs Behavior: self-administered operational specificity - own/seek/\n  acquire a method, set a date, write a note means Behavior.\n- Behavior vs Attempt: tense/completion - the act occurred (incl. aborted), or\n  "again" after a real act, means Attempt.'
