import re
RAW_TRAIN = 'data/raw/train.xlsx'
RAW_LEADERBOARD = 'data/raw/leaderboard.xlsx'
SHEET = 'Sheet1'
RAW_SHA256 = {'train.xlsx': 'b5d1704c01d6ba5e02ba4fe16775ffccfb386890fa0ffba60dc4e3b61a7396f6', 'leaderboard.xlsx': '3ac9367408f20dba66f8b4f3bf80bb3ba53851b78069997514e83f6ca7b16c97'}
TRAIN_COLUMNS = ['row_id', 'anon_user_id', 'post_id', 'post', 'suicide risk', 'evidence for suicide risk level', 'factors']
LB_COLUMNS = ['row_id', 'anon_user_id', 'post_id', 'post']
RISK_CLASSES = ('Indicator', 'Ideation', 'Behavior', 'Attempt')
RISK_ORD = {c: i for i, c in enumerate(RISK_CLASSES)}
FACTORS_24 = ('hopelessness', 'emotion dysregulation', 'poor social support', 'low self-esteem', 'suicide means (with access)', 'mental health issues', 'prior self-harm or suicidal thought/attempt', 'interpersonal difficulty', 'stressful life event', 'dysfunctional family', 'interpersonal violence', 'physical health/characteristic', 'traumatic experience', 'low socio-economic status', 'cognitive deficits', 'substance use', 'poor school performance', "exposure to others' suicide", 'sexual orientation related issues', 'coping strategy', 'psychological capital', 'social support', 'sense of responsibility', 'meaning in life')
FACTOR_INDEX = {f: i for i, f in enumerate(FACTORS_24)}
FACTOR_SUPPORTS = {'hopelessness': 745, 'emotion dysregulation': 542, 'poor social support': 501, 'low self-esteem': 475, 'suicide means (with access)': 292, 'mental health issues': 228, 'prior self-harm or suicidal thought/attempt': 215, 'interpersonal difficulty': 195, 'stressful life event': 182, 'dysfunctional family': 118, 'interpersonal violence': 83, 'physical health/characteristic': 78, 'traumatic experience': 64, 'low socio-economic status': 54, 'cognitive deficits': 33, 'substance use': 33, 'poor school performance': 16, "exposure to others' suicide": 14, 'sexual orientation related issues': 8, 'coping strategy': 443, 'psychological capital': 238, 'social support': 112, 'sense of responsibility': 58, 'meaning in life': 45}
LEAK_RE = re.compile('^.*?phrases that lead to this assessment:\\s*', re.S)
LEAKAGE_ROWS = frozenset({'P01318', 'P01495'})
CHAR_MAP = {'’': "'", '‘': "'", '“': '"', '”': '"', '…': '...', '\xa0': ' '}
EDGE_PUNCT_RE = re.compile('[.!?,;:"]+$')
GAP_RE = re.compile('\\s*(?:\\.\\.\\.|…)\\s*')
NEAR_DUP_MERGES = (frozenset({'P00758', 'P00759', 'P00761'}), frozenset({'P00735', 'P00736', 'P00737', 'P00738'}), frozenset({'P01334', 'P01335'}), frozenset({'P00137', 'P01626'}), frozenset({'P00094', 'P00095', 'P00098', 'P00101', 'P00103', 'P00108', 'P00113', 'P00114', 'P00121', 'P02065', 'P02066', 'P02067', 'P02068', 'P00552'}))
PINNED_RESOLUTIONS = {'P00758': 'Behavior', 'P00759': 'Behavior', 'P00761': 'Behavior', 'P00735': 'Attempt', 'P00736': 'Attempt', 'P00737': 'Attempt', 'P00738': 'Attempt', 'P01334': 'Behavior', 'P01335': 'Behavior', 'P00137': 'Indicator', 'P01626': 'Indicator', 'P00094': 'Indicator', 'P02068': 'Indicator', 'P00552': 'Indicator'}
LB_DUP_PAIRS = (('P00010', 'P00011'), ('P00943', 'P00944'))
LB_KNOWN = {'P01130': {'risk': 'Attempt', 'evidence_candidates': ['just overdosed', 'overdosed'], 'factors': 'model'}, 'P00940': {'risk': 'Behavior', 'evidence_candidates': ['plan on killing myself soon'], 'factors': 'model'}, 'P00941': {'risk': 'Behavior', 'evidence_candidates': ['plan on killing myself soon'], 'factors': 'model'}, 'P00942': {'risk': 'Behavior', 'evidence_candidates': ['plan on killing myself soon'], 'factors': 'model'}}
U0123_BLOCK = tuple((f'P{i:05d}' for i in range(8, 13)))
U0161_BLOCK = ('P00941', 'P00940', 'P00942')
N_FOLDS = 5
FOLD_SEED = 42
MIN_ATTEMPT_PER_FOLD = 15
TARGET_SCHEMAS = ('v1', 'v2')
TARGET_SCHEMA = 'v2'
SFT_INSTRUCTION_V1 = 'Read the Reddit post marked [FOCAL POST] (from r/SuicideWatch) and assess it. Respond with a JSON object with keys: risk (one of Indicator, Ideation, Behavior, Attempt), evidence (list of short verbatim phrases copied exactly from the focal post that support the risk level; empty list for Indicator), and factors (list of applicable factor categories; may be empty).'
SFT_INSTRUCTION_V2 = 'Read the Reddit post marked [FOCAL POST] (from r/SuicideWatch) and assess it. Respond with a JSON object with keys, in this order: evidence (list of short verbatim phrases copied exactly from the focal post that support the risk level; empty list for Indicator), factors (an object mapping every one of the 24 factor category names to true or false, all 24 keys always present in the fixed taxonomy order), and risk (your concluding assessment: one of Indicator, Ideation, Behavior, Attempt).'
SFT_INSTRUCTIONS = {'v1': SFT_INSTRUCTION_V1, 'v2': SFT_INSTRUCTION_V2}
SFT_INSTRUCTION = SFT_INSTRUCTIONS[TARGET_SCHEMA]
CTX_N_PREV = 2
CTX_N_NEXT = 1
CTX_NEIGHBOR_CHARS = 300
FOCAL_BUDGET_TOKENS = 1024
HEAD_FRAC = 0.6
TRUNCATION_MARKER = '\n[... POST TRUNCATED ...]\n'
EXPECTED = {'train_shape': (1635, 7), 'lb_shape': (378, 4), 'n_train_users': 153, 'n_lb_users': 36, 'risk_raw_variants': 10, 'risk_counts': {'Indicator': 611, 'Ideation': 519, 'Behavior': 391, 'Attempt': 114}, 'evidence_nan_rows': 5, 'evidence_none_cells': 583, 'gold_spans': 1832, 'evidence_posts': 1046, 'no_evidence_posts': 589, 'indicator_with_evidence': 22, 'max_span_tokens': 19, 'factor_parse_failures': 0, 'empty_factor_lists': 128, 'max_factor_repeat': 38, 'max_distinct_factors': 18, 'exact_dup_groups': 29, 'exact_dup_rows': 76, 'ladder': {'exact': 1638, 'casefold': 23, 'normalized': 90, 'trimmed': 26}, 'max_unmatched_spans': 60, 'multi_occurrence_spans': 59, 'empty_pred_phrase_f1': 589 / 1635, 'min_scorer_ceiling': 0.98, 'max_sft_skipped_unalignable': 6, 'max_sft_skipped_truncated': 0}
