import os
from prep import constants as PC
BASE_MODEL = os.environ.get('GEMMA_MODEL', '')
TINY_MODEL = 'Qwen/Qwen2.5-0.5B-Instruct'
ARMS = ('real_only', 'synthetic', 'repeated_real')
LAUNCH_ARMS = ('real_only', 'synthetic', 'repeated_real')
SYNTH_ARMS = ('synthetic', 'repeated_real')
TRAIN_SEEDS = (1, 2)
SEED_BASE = 20260801
N_FOLDS = PC.N_FOLDS
SFT_DIR = 'data/processed/sft'
ARMS_DIR = 'data/synthetic/arms'
RUNS_DIR = 'runs'
MAX_SEQ_LEN = 2432
MICRO_BATCH = 1
GRAD_ACCUM = 16
TOTAL_STEPS = 160
CHECKPOINT_STEPS = (40, 80, 120, 160)
LR = 0.0001
LR_SCHEDULE = 'cosine_with_min_lr'
MIN_LR_RATIO = 0.1
WARMUP_STEPS = 10
WEIGHT_DECAY = 0.0
MAX_GRAD_NORM = 1.0
ADAM_BETAS = (0.9, 0.999)
PRECISION = 'bf16'
ATTN_IMPL = 'flash_attention_2'
ATTN_IMPL_FALLBACK = 'sdpa'
GRAD_CKPT = True
LOAD_IN_4BIT = False
BNB_4BIT_QUANT_TYPE = 'nf4'
BNB_4BIT_DOUBLE_QUANT = True
LORA_R = 16
LORA_ALPHA = 32
LORA_DROPOUT = 0.05
LORA_TARGETS = ('q_proj', 'k_proj', 'v_proj', 'o_proj', 'gate_proj', 'up_proj', 'down_proj')
MAX_NEW_TOKENS = 320
GEN_TEMPERATURE = 0.0
RETRY_TEMPS = (0.3, 0.7)
LOGPROBS_TOPK = 20
GUIDED_DECODING = False
GUIDED_TRIGGER = 0.005
VLLM_GPU_MEM_UTIL = 0.92
VLLM_MAX_LORAS = 2
VLLM_MAX_MODEL_LEN = 2560
VLLM_QUANTIZATION = None
VLLM_TENSOR_PARALLEL = 2
FALLBACK_PRED = {'risk': 'Indicator', 'spans': (), 'factors': ()}
EE_PRIMARY = 'ee1'
BOOTSTRAP_B = 2000
BOOTSTRAP_SEED = 20260815
SHIP_BAR = 0.01
THRESH_FALLBACK = 0.5
THRESH_TIEBREAK = 'highest'
THRESH_BAG_N_BOOT = 200
THRESH_BAG_SEED = 20260815
ENSEMBLE_MIN_GAIN = 0.002
ENSEMBLE_MIN_POSITIVE_FRACTION = 0.8
ORPHAN_GOLD_ROWS = ('P00371', 'P01754', 'P02269', 'P02353')
